# Site settings
title: Rahul purohit
description: Rahul Purohit | Portfolio 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rahul Purohit
user_description: Entrepreneur-minded Software Engineer with 3.5+ years of experience in the IT industry, combining a technology-focus with excellent problem solving, team building and product management skills.Consulting with clients to scope out and deliver customized solutions. Helping clients, sales, and marketing teams to understand technical issues and technical teams to understand client requirements.
user_title: Software Developer
email: rahulpuroht@gmail.com
twitter_username: rahul_msp
github_username:  rahulpuroht
# Google-analytics
google-analytics:
  id: "UA-124945877-1"

exclude: ['package.json', 'src' , 'node_modules']
